spring:
  datasource:
    url: jdbc:mysql://192.168.125.128:3306/blog_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root  # 请根据实际情况修改用户名
    password: root  # 请根据实际情况修改密码
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
  basic:
    enable: false
  openapi:
    title: 星喵博客系统 API
    description: 现代化、高性能、易扩展的博客系统后端API接口文档
    email: admin@xingmiao.com
    concat: 星喵博客系统
    url: https://blog.xingmiao.com
    version: 1.0.0
    license: MIT License
    license-url: https://opensource.org/licenses/MIT
    terms-of-service-url: https://blog.xingmiao.com/terms
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.xingmiao.blog.controller

# 博客作者配置
blog:
  author:
    username: admin
    nickname: 星喵博客
    bio: 欢迎来到我的博客！
    avatar-url: https://via.placeholder.com/150x150?text=星喵
    email: admin@xingmiao.com
    website: https://blog.xingmiao.com
    # export BLOG_AUTHOR_PASSWORD=your_real_password
    password: ${BLOG_AUTHOR_PASSWORD:dev_password}
    password-enabled: true
  security:
    jwt:
      # 生产环境请使用强密钥，可以通过环境变量设置
      # export BLOG_JWT_SECRET=your_strong_secret_key_here
      secret: ${BLOG_JWT_SECRET:defaultSecretKeyForDevelopmentOnlyChangeInProduction}
      # 默认令牌过期时间（秒）
      default-ttl: 86400


github:
  token: #填写自己的密钥
